name: "Pull Request Docs Check"

## Only update on change to masters branch
on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    ## Pulling the package
    - uses: actions/checkout@v2

    ## Running sphinx
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "./"

    ## Deploying the generated documents to github pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html/

